name=BaruchServo
version=0.0.1
author=Nathan-Busse
maintainer=Nathan-Busse <aboutnathangrahambusse.web.app>
sentence=BaruchServo
paragraph=BaruchServo
category=Device Control
url=https://github.com/Nathan-Busse/Baruch_RP_1
architectures=*
depends=Baruch_BusIO
